import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";
import NavBar from "./_components/NavBar";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  head: [
    {
      tag: "meta",
      props: {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
        links: [{ rel: "preconnect", href: "https://fonts.googleapis.com" }, { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "" }, { rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=Jersey+25&display=swap" } ],
        
      },
    },
  ],
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        
        <TRPCReactProvider>
          <NavBar />{children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
